In [1]:
import numpy as np
import pandas as pd

In [2]:
url='https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'

In [3]:
sms=pd.read_table(filepath_or_buffer=url,header=None, names=['label','message'])

In [4]:
sms.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
simple_train = ['call you tonight', 'call me a cab', 'please call me...please']

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
vect = CountVectorizer()

In [9]:
print("Vect Properties are: \n", vect, "\n")

Vect Properties are: 
 CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None) 



In [10]:
print("Vect Output Properties are: \n", dir(vect), "\n")

Vect Output Properties are: 
 ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_char_ngrams', '_char_wb_ngrams', '_check_stop_words_consistency', '_check_vocabulary', '_count_vocab', '_get_param_names', '_get_tags', '_limit_features', '_more_tags', '_sort_features', '_validate_custom_analyzer', '_validate_params', '_validate_vocabulary', '_warn_for_unused_params', '_white_spaces', '_word_ngrams', 'analyzer', 'binary', 'build_analyzer', 'build_preprocessor', 'build_tokenizer', 'decode', 'decode_error', 'dtype', 'encoding', 'fit', 'fit_transform', 'get_feature_names', 'get_params', 'get_stop_words', 'input', 'inverse_transform', 'lowercase', 'max_df', 'max_features

In [11]:
vect.fit(simple_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [13]:
print("Examining the Fitted Vocabulary :\n", vect.get_feature_names(),"\n")

Examining the Fitted Vocabulary :
 ['cab', 'call', 'me', 'please', 'tonight', 'you'] 



In [14]:
simple_train_dtm_parse = vect.transform(simple_train)

In [15]:
print("The Type of the Parse Matrix is :\n", type(simple_train_dtm_parse),"\n")

The Type of the Parse Matrix is :
 <class 'scipy.sparse.csr.csr_matrix'> 



In [16]:
print("The Document Term Sparse Matrix is :\n", simple_train_dtm_parse, "\n")

The Document Term Sparse Matrix is :
   (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2 



In [17]:
simple_train_dtm_dense = simple_train_dtm_parse.toarray()

In [18]:
print("The Type of the Dense Matrix is :\n", type(simple_train_dtm_dense),"\n")

The Type of the Dense Matrix is :
 <class 'numpy.ndarray'> 



In [19]:
print("The Document Term Dense Matrix is :\n", simple_train_dtm_dense, "\n")

The Document Term Dense Matrix is :
 [[0 1 0 0 1 1]
 [1 1 1 0 0 0]
 [0 1 1 2 0 0]] 



In [20]:
print("Printing the Dense Matrix in a DataFrame \n", pd.DataFrame(data=simple_train_dtm_dense,index=simple_train,columns=vect.get_feature_names()), "\n")

Printing the Dense Matrix in a DataFrame 
                          cab  call  me  please  tonight  you
call you tonight           0     1   0       0        1    1
call me a cab              1     1   1       0        0    0
please call me...please    0     1   1       2        0    0 



In [21]:
simple_test = ['please don\'t call me']

In [22]:
simple_test_dtm = vect.transform(simple_test)

In [23]:
print("The Sparse Matrix for the Test Data Set is :\n", simple_test_dtm, "\n")

The Sparse Matrix for the Test Data Set is :
   (0, 1)	1
  (0, 2)	1
  (0, 3)	1 



In [24]:
print("The Dense Matrix for the Test Data Set is :\n", simple_test_dtm.toarray(), "\n")

The Dense Matrix for the Test Data Set is :
 [[0 1 1 1 0 0]] 



In [25]:
print("Printing the Dense Matrix in a DataFrame for the Test Data \n", pd.DataFrame(data=simple_test_dtm.toarray(),index=simple_test,columns=vect.get_feature_names()), "\n")

Printing the Dense Matrix in a DataFrame for the Test Data 
                       cab  call  me  please  tonight  you
please don't call me    0     1   1       1        0    0 



In [28]:
print("The shape of the Input Message is :\n", X.shape, "\n")

print("The shape of the output Variable is \n", y.shape, "\n")

The shape of the Input Message is :
 (5572,) 

The shape of the output Variable is 
 (5572,) 



In [33]:
sms['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [35]:
from sklearn.model_selection import train_test_split

In [40]:
sms['label_num']=sms['label'].map({'ham':0,'spam':1})

In [41]:
X = sms['message']

In [42]:
y= sms['label_num']

In [43]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,random_state=1)

In [44]:
print("The Shape of the Training Input Data is :\n", Xtrain.shape)
print("The Shape of the Testing Input Data is :\n", Xtest.shape)
print("The Shape of the Training Output Data is :\n", ytrain.shape)
print("The Shape of the Testing Output Data is :\n", ytest.shape)

The Shape of the Training Input Data is :
 (4179,)
The Shape of the Testing Input Data is :
 (1393,)
The Shape of the Training Output Data is :
 (4179,)
The Shape of the Testing Output Data is :
 (1393,)


In [47]:
Xtrain

710     4mths half price Orange line rental & latest c...
3740                           Did you stitch his trouser
2711    Hope you enjoyed your new content. text stop t...
3155    Not heard from U4 a while. Call 4 rude chat pr...
3748    Ü neva tell me how i noe... I'm not at home in...
                              ...                        
905     We're all getting worried over here, derek and...
5192    Oh oh... Den muz change plan liao... Go back h...
3980    CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
235     Text & meet someone sexy today. U can find a d...
5157                              K k:) sms chat with me.
Name: message, Length: 4179, dtype: object

In [48]:
vect = CountVectorizer()

In [49]:
Xtrain_dtm_parse = vect.fit_transform(Xtrain)

In [50]:
print("The Sparse Matrix for the Training Data is :\n", Xtrain_dtm_parse, "\n")

The Sparse Matrix for the Training Data is :
   (0, 509)	1
  (0, 3181)	1
  (0, 5193)	1
  (0, 4781)	1
  (0, 3971)	1
  (0, 5479)	1
  (0, 3880)	1
  (0, 1572)	1
  (0, 4987)	1
  (0, 2864)	2
  (0, 3170)	1
  (0, 7424)	1
  (0, 4983)	1
  (0, 264)	1
  (0, 1552)	1
  (0, 4375)	1
  (0, 4743)	1
  (0, 50)	1
  (0, 6656)	1
  (0, 6892)	1
  (0, 4662)	1
  (0, 4779)	1
  (0, 2022)	1
  (1, 2222)	1
  (1, 7420)	1
  :	:
  (4177, 4255)	1
  (4177, 4446)	1
  (4177, 4778)	1
  (4177, 2744)	1
  (4177, 254)	1
  (4177, 5490)	1
  (4177, 2556)	1
  (4177, 4508)	1
  (4177, 6034)	1
  (4177, 6662)	1
  (4177, 307)	1
  (4177, 837)	1
  (4177, 3700)	1
  (4177, 5796)	1
  (4177, 358)	1
  (4177, 4934)	1
  (4177, 2453)	1
  (4177, 2097)	1
  (4177, 5403)	1
  (4177, 2786)	1
  (4177, 6577)	1
  (4178, 1691)	1
  (4178, 4238)	1
  (4178, 7257)	1
  (4178, 5999)	1 



In [51]:
print("The Dense Matrix for the Training Data is :\n", Xtrain_dtm_parse.toarray(), "\n")

The Dense Matrix for the Training Data is :
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 



In [52]:
fitted_vocab = vect.get_feature_names()

In [53]:
print("The Fitted Vocabulory is :\n", fitted_vocab, "\n")

The Fitted Vocabulory is :
 ['00', '000', '008704050406', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090201529', '07090298926', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '07786200117', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705', '08000938767', '08001950382', '08002888812', '08002986030', '08002986906', '08002988890', '08006344447', '0808', '08081263000', '08081560665', '0825', '083', '0844', '08448714184', '0845', '08450542832', '08452810071', '08452810073', '08452810075over18', '0870', '08700435505150p', '08700469649', '08700621170150p', '08701213186', '08701417012', '08701417012150p',

In [54]:
print("The DataFrame Matrix for the Dense Matrix Train Data is :\n", pd.DataFrame(data=Xtrain_dtm_parse.toarray(),index =Xtrain ,columns=fitted_vocab))

The DataFrame Matrix for the Dense Matrix Train Data is :
                                                     00  000  008704050406  \
message                                                                     
4mths half price Orange line rental & latest ca...   0    0             0   
Did you stitch his trouser                           0    0             0   
Hope you enjoyed your new content. text stop to...   0    0             0   
Not heard from U4 a while. Call 4 rude chat pri...   0    0             0   
Ü neva tell me how i noe... I'm not at home in ...   0    0             0   
...                                                 ..  ...           ...   
We're all getting worried over here, derek and ...   0    0             0   
Oh oh... Den muz change plan liao... Go back ha...   0    0             0   
CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C ...   0    0             0   
Text & meet someone sexy today. U can find a da...   0    0             0   
K k:) sms chat wi

In [55]:
Xtest_dtm_parse = vect.transform(Xtest)

In [56]:
print("The Sparse Matrix for the Testing Data is :\n", Xtest_dtm_parse, "\n")

The Sparse Matrix for the Testing Data is :
   (0, 1538)	1
  (0, 5189)	1
  (0, 6542)	1
  (0, 7405)	1
  (1, 1016)	1
  (1, 3050)	1
  (1, 4163)	1
  (1, 4238)	1
  (1, 4370)	1
  (1, 5200)	1
  (1, 6656)	1
  (1, 7407)	1
  (1, 7420)	1
  (2, 986)	1
  (2, 3244)	1
  (2, 7162)	1
  (3, 3237)	1
  (4, 887)	2
  (4, 1060)	1
  (4, 1595)	1
  (4, 2066)	1
  (4, 2833)	1
  (4, 3388)	1
  (4, 3623)	1
  (4, 3921)	1
  :	:
  (1391, 4373)	1
  (1391, 4413)	1
  (1391, 4441)	1
  (1391, 4743)	1
  (1391, 4778)	1
  (1391, 6017)	1
  (1391, 6057)	1
  (1391, 6829)	1
  (1391, 6904)	1
  (1391, 7012)	1
  (1391, 7120)	1
  (1391, 7230)	2
  (1391, 7239)	1
  (1391, 7287)	1
  (1391, 7357)	1
  (1392, 848)	1
  (1392, 2400)	1
  (1392, 2873)	1
  (1392, 3158)	1
  (1392, 4238)	1
  (1392, 4255)	2
  (1392, 4487)	1
  (1392, 4802)	1
  (1392, 5565)	1
  (1392, 7075)	1 



In [57]:
print("The Dense Matrix for the Training Data is :\n", Xtest_dtm_parse.toarray(), "\n")

The Dense Matrix for the Training Data is :
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 



In [58]:
print("The DataFrame Matrix for the Dense Matrix Test Data is :\n", pd.DataFrame(data=Xtest_dtm_parse.toarray(),index =Xtest ,columns=fitted_vocab), "\n")

The DataFrame Matrix for the Dense Matrix Test Data is :
                                                     00  000  008704050406  \
message                                                                     
Yep, by the pretty sculpture                         0    0             0   
Yes, princess. Are you going to make me moan?        0    0             0   
Welp apparently he retired                           0    0             0   
Havent.                                              0    0             0   
I forgot 2 ask ü all smth.. There's a card on d...   0    0             0   
...                                                 ..  ...           ...   
At home also.                                        0    0             0   
Hope you are having a great day.                     0    0             0   
Message:some text missing* Sender:Name Missing*...   0    0             0   
WIN: We have a winner! Mr. T. Foley won an iPod...   0    0             0   
U meet other fren 

In [59]:
from sklearn.naive_bayes import MultinomialNB

In [60]:
mnb=MultinomialNB()  

In [61]:
mnb.fit(Xtrain_dtm_parse,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [62]:
ypred=mnb.predict(Xtest_dtm_parse)

In [63]:
print('The Prediction are :\n', ypred,"\n")

The Prediction are :
 [0 0 0 ... 0 1 0] 



In [64]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [65]:
accuracy = accuracy_score(ytest,ypred)

In [66]:
print("The Accuracy of the Multinomail Bayes Model is :\n", accuracy, "\n")

The Accuracy of the Multinomail Bayes Model is :
 0.9885139985642498 



In [67]:
confusion =confusion_matrix(ytest,ypred)

In [68]:
print("The Confusion Metrics is :\n", pd.DataFrame(data=confusion,index=['ham','spam'],columns=['Negative','Positive']), "\n")

The Confusion Metrics is :
       Negative  Positive
ham       1203         5
spam        11       174 



In [70]:
# False Positive
Xtest[ypred>ytest.values]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [71]:
# False Negatives
Xtest[ypred<ytest.values]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [84]:
# True Positives
Xtest[ytest==ypred]

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
                              ...                        
3207                                        At home also.
4655                     Hope you are having a great day.
1140    Message:some text missing* Sender:Name Missing...
1793    WIN: We have a winner! Mr. T. Foley won an iPo...
1710    U meet other fren dun wan meet me ah... Muz b ...
Name: message, Length: 1377, dtype: object

In [83]:
# True Positives
Xtest[(ytest==1) & (ypred==1)]

147     FreeMsg Why haven't you replied to my text? I'...
4517    Congrats! 2 mobile 3G Videophones R yours. cal...
3316    FREE MESSAGE Activate your 500 FREE Text Messa...
1929    Call from 08702490080 - tells u 2 call 0906635...
1745    Someone has conacted our dating service and en...
                              ...                        
5178    SMS AUCTION - A BRAND NEW Nokia 7250 is up 4 a...
1961    Guess what! Somebody you know secretly fancies...
1714    Hard LIVE 121 chat just 60p/min. Choose your g...
1463    09066362231 URGENT! Your mobile No 07xxxxxxxxx...
1793    WIN: We have a winner! Mr. T. Foley won an iPo...
Name: message, Length: 174, dtype: object

In [82]:
# True Negatives
Xtest[(ytest==0) & (ypred==0)]

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
                              ...                        
4285    Yes. I come to nyc for audiitions and am tryin...
3207                                        At home also.
4655                     Hope you are having a great day.
1140    Message:some text missing* Sender:Name Missing...
1710    U meet other fren dun wan meet me ah... Muz b ...
Name: message, Length: 1203, dtype: object

In [85]:
ypred_prob = mnb.predict_proba(Xtest_dtm_parse)

In [86]:
print("The Probability Distribution is :\n", ypred_prob,"\n")

The Probability Distribution is :
 [[9.97122551e-01 2.87744864e-03]
 [9.99981651e-01 1.83488846e-05]
 [9.97926987e-01 2.07301295e-03]
 ...
 [9.99998910e-01 1.09026171e-06]
 [1.86697467e-10 1.00000000e+00]
 [9.99999996e-01 3.98279868e-09]] 



In [87]:
ypred_prob_positive =mnb.predict_proba(Xtest_dtm_parse)[:,1]

In [88]:
print("The Probability Distribution for the Positive Response are:\n", ypred_prob_positive,"\n")

The Probability Distribution for the Positive Response are:
 [2.87744864e-03 1.83488846e-05 2.07301295e-03 ... 1.09026171e-06
 1.00000000e+00 3.98279868e-09] 



In [90]:
from sklearn.metrics import roc_auc_score

In [91]:
auc_score = roc_auc_score(np.array(ytest),ypred_prob_positive)

In [92]:
print("AUC Score for Mnb :\n", auc_score, "\n")

AUC Score for Mnb :
 0.9866431000536962 



In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
logreg=LogisticRegression()

In [100]:
%time logreg.fit(Xtrain_dtm_parse,ytrain)

Wall time: 98.7 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [101]:
ypred_class=logreg.predict(Xtest_dtm_parse)

In [102]:
ypred_prob_positive_logreg=logreg.predict_proba(Xtest_dtm_parse)[:,1]

In [103]:
ypred_prob_positive_logreg

array([0.00959377, 0.00295662, 0.00452424, ..., 0.031302  , 0.99748962,
       0.00119521])

In [104]:
accuracy_score(ytest,ypred_class)

0.9877961234745154

In [105]:
roc_auc_score(ytest,ypred_prob_positive_logreg)

0.9936280651512441

In [107]:
print("Printing the First 50 fitted Vocabularies , Tokens \n", vect.get_feature_names()[0:50],"\n")

Printing the First 50 fitted Vocabularies , Tokens 
 ['00', '000', '008704050406', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090201529', '07090298926', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '07786200117', '078', '07801543489', '07808', '07808247860', '07808726822', '07815296484', '07821230901', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705'] 



In [108]:
print("Printing the Last 50 fitted Vocabularies , Tokens \n", vect.get_feature_names()[-50:],"\n")

Printing the Last 50 fitted Vocabularies , Tokens 
 ['yer', 'yes', 'yest', 'yesterday', 'yet', 'yetunde', 'yijue', 'ym', 'ymca', 'yo', 'yoga', 'yogasana', 'yor', 'yorge', 'you', 'youdoing', 'youi', 'youphone', 'your', 'youre', 'yourjob', 'yours', 'yourself', 'youwanna', 'yowifes', 'yoyyooo', 'yr', 'yrs', 'ything', 'yummmm', 'yummy', 'yun', 'yunny', 'yuo', 'yuou', 'yup', 'zac', 'zaher', 'zealand', 'zebra', 'zed', 'zeros', 'zhong', 'zindgi', 'zoe', 'zoom', 'zouk', 'zyada', 'èn', '〨ud'] 



In [110]:
ham_spam_dist = pd.DataFrame(data=mnb.feature_count_,index=['Ham','Spam'],columns=vect.get_feature_names())

In [111]:
print("Ham and Spam distribution is :\n",ham_spam_dist ,"\n")

Ham and Spam distribution is :
        00   000  008704050406  0121  01223585236  01223585334  0125698789  \
Ham   0.0   0.0           0.0   0.0          0.0          0.0         1.0   
Spam  5.0  23.0           2.0   1.0          1.0          2.0         0.0   

       02  0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  \
Ham   0.0   0.0          0.0  ...  0.0    1.0    1.0     2.0  1.0   1.0   0.0   
Spam  4.0   3.0          1.0  ...  6.0    0.0    0.0     0.0  1.0   0.0   1.0   

      zyada   èn  〨ud  
Ham     1.0  1.0  1.0  
Spam    0.0  0.0  0.0  

[2 rows x 7456 columns] 



In [112]:
ham_spam_dist

00   000  008704050406  0121  01223585236  01223585334  0125698789  \
Ham   0.0   0.0           0.0   0.0          0.0          0.0         1.0   
Spam  5.0  23.0           2.0   1.0          1.0          2.0         0.0   

       02  0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  \
Ham   0.0   0.0          0.0  ...  0.0    1.0    1.0     2.0  1.0   1.0   0.0   
Spam  4.0   3.0          1.0  ...  6.0    0.0    0.0     0.0  1.0   0.0   1.0   

      zyada   èn  〨ud  
Ham     1.0  1.0  1.0  
Spam    0.0  0.0  0.0  

[2 rows x 7456 columns]

In [116]:
ham_dist = mnb.feature_count_[0,:]

In [117]:
print("Ham distribution is :\n", pd.DataFrame(data=ham_dist,index=vect.get_feature_names(),columns=['Ham']),"\n")

Ham distribution is :
               Ham
00            0.0
000           0.0
008704050406  0.0
0121          0.0
01223585236   0.0
...           ...
zoom          1.0
zouk          0.0
zyada         1.0
èn            1.0
〨ud           1.0

[7456 rows x 1 columns] 



In [118]:
spam_dist = mnb.feature_count_[1,:]

In [119]:
print("Spam distribution is :\n", pd.DataFrame(data=spam_dist,index=vect.get_feature_names(),columns=['Spam']),"\n")

Spam distribution is :
               Spam
00             5.0
000           23.0
008704050406   2.0
0121           1.0
01223585236    1.0
...            ...
zoom           0.0
zouk           1.0
zyada          0.0
èn             0.0
〨ud            0.0

[7456 rows x 1 columns] 



In [120]:
ham_spam_dist_transpose = ham_spam_dist.T

In [121]:
print("The Random Dataset and the Response count are :\n",ham_spam_dist_transpose.sample(n=5,random_state=6),"\n")

The Random Dataset and the Response count are :
                Ham  Spam
very          64.0   2.0
nasty          1.0   1.0
villa          0.0   1.0
beloved        1.0   0.0
textoperator   0.0   2.0 



In [126]:
logreg.coef_

array([[ 0.29856208,  0.55458094,  0.00508105, ..., -0.00835305,
        -0.07762267, -0.00539686]])

In [123]:
logreg.coef_.shape

(1, 7456)

In [125]:
len(vect.get_feature_names())

7456

In [127]:
ham_spam_dist_transpose

Ham  Spam
00            0.0   5.0
000           0.0  23.0
008704050406  0.0   2.0
0121          0.0   1.0
01223585236   0.0   1.0
...           ...   ...
zoom          1.0   0.0
zouk          0.0   1.0
zyada         1.0   0.0
èn            1.0   0.0
〨ud           1.0   0.0

[7456 rows x 2 columns]

In [128]:
print("Ham and Spam overall counts are : \n", pd.DataFrame(data=mnb.class_count_,index=['Ham', 'Spam']),"\n")

Ham and Spam overall counts are : 
            0
Ham   3617.0
Spam   562.0 



In [129]:
mnb.class_count_

array([3617.,  562.])

TypeError: 'NoneType' object is not callable

In [132]:
ham_spam_dist_transpose['Ham'] = ham_spam_dist_transpose['Ham']+1
ham_spam_dist_transpose['Spam'] = ham_spam_dist_transpose['Spam']+1

In [133]:
ham_spam_dist_transpose

Ham  Spam
00            1.0   6.0
000           1.0  24.0
008704050406  1.0   3.0
0121          1.0   2.0
01223585236   1.0   2.0
...           ...   ...
zoom          2.0   1.0
zouk          1.0   2.0
zyada         2.0   1.0
èn            2.0   1.0
〨ud           2.0   1.0

[7456 rows x 2 columns]

In [135]:
print("The New Random Dataset and the Response count are :\n",ham_spam_dist_transpose.sample(n=5,random_state=6),"\n")

The New Random Dataset and the Response count are :
                Ham  Spam
very          65.0   3.0
nasty          2.0   2.0
villa          1.0   2.0
beloved        2.0   1.0
textoperator   1.0   3.0 



In [136]:
ham_spam_dist_transpose['Ham'] = ham_spam_dist_transpose['Ham']/mnb.class_count_[0]
ham_spam_dist_transpose['Spam'] = ham_spam_dist_transpose['Spam']/mnb.class_count_[1]

In [137]:
print("The Ham Spam distribution from the random dataset is now :\n", ham_spam_dist_transpose.sample(n=5,random_state=6), "\n")

The Ham Spam distribution from the random dataset is now :
                    Ham      Spam
very          0.017971  0.005338
nasty         0.000553  0.003559
villa         0.000276  0.003559
beloved       0.000553  0.001779
textoperator  0.000276  0.005338 



In [138]:
ham_spam_dist_transpose['Spam Ratio'] = ham_spam_dist_transpose['Spam']/ham_spam_dist_transpose['Ham']

In [139]:
print("The Sorted Spam Ratio is :\n", ham_spam_dist_transpose.sort_values(by='Spam Ratio',ascending=False),"\n")

The Sorted Spam Ratio is :
                  Ham      Spam  Spam Ratio
claim       0.000276  0.158363  572.798932
prize       0.000276  0.135231  489.131673
150p        0.000276  0.087189  315.361210
tone        0.000276  0.085409  308.925267
guaranteed  0.000276  0.076512  276.745552
...              ...       ...         ...
da          0.032900  0.001779    0.054084
she         0.035665  0.001779    0.049891
he          0.047000  0.001779    0.037858
lt          0.064142  0.001779    0.027741
gt          0.064971  0.001779    0.027387

[7456 rows x 3 columns] 



In [140]:
print("Checking for the Spam Ratio for a Particular Word :\n", ham_spam_dist_transpose.loc['dating','Spam Ratio'],'\n')

Checking for the Spam Ratio for a Particular Word :
 83.66725978647686 



In [141]:
Xsample1 = '''You have won a claim worth prize 400 dollars and in this regards you are requested to send a deposit money of $ 500 and on the
reciept of the money, you will be awarded a guaranteed worth of prize money'''
Xsample2 = '''You are a good example to all the students in this class. I am very happy for your achievement and I wish you
all the success in your future endeavor'''

In [142]:
Xsampledf =pd.Series(Xsample1)

In [143]:
Xsample_dtm_parse = vect.transform(Xsampledf)

In [144]:
print("The Predicted Keyword is :\n",mnb.predict(Xsample_dtm_parse), "\n")

The Predicted Keyword is :
 [1] 

